export const civsAry = [
  'Spanish',
  'British',
  'French',
  'Portuguese',
  'Dutch',
  'Russians',
  'Germans',
  'Ottomans',
  'XPIroquois',
  'XPSioux',
  'XPAztec',
  'Japanese',
  'Chinese',
  'Indians',
  'DEInca',
  'DESwedish',
  'DEAmericans',
  'DEHausa',
  'DEEthiopians',
  'DEMexicans',
  'DEItalians',
  'DEMaltese',
]

export const isBonusIcon = [
  'AbstractInfantry',
  'AbstractHeavyInfantry',
  'AbstractLightInfantry',
  'AbstractCavalry',
  'AbstractHeavyCavalry',
  'AbstractLightCavalry',
  'AbstractArtillery',
  'AbstractVillager',
  'Building',
  'AbstractPet',
  'AbstractCoyoteMan',
  'Mercenary',
  'Hero',
  'Ship',
  'AbstractSiegeTrooper',
  'AbstractHandInfantry',
  'AbstractNativeWarrior',
  'Huntable',
  'Guardian',
]

export const iconAry = [
  'exp',
  'age0',
  'age1',
  'age2',
  'age3',
  'age4',
  'food',
  'gold',
  'wood',
  'time',
  'range',
  'rof',
  'area',
  'Siege',
  'Hand',
  'Ranged',
  'AbstractArtillery',
  'AbstractHandInfantry',
  'AbstractHeavyInfantry',
  'AbstractRangedShockInfantry',
  'AbstractInfantry',
  'AbstractNativeWarrior',
  'AbstractCoyoteMan',
  'AbstractHeavyCavalry',
  'AbstractLightCavalry',
  'AbstractLightInfantry',
  'AbstractCavalry',
  'AbstractRangedCavalry',
  'AbstractHandCavalry',
  'AbstractSiegeTrooper',
  'AbstractVillager',
  'AbstractSkirmisher',
  'AbstractPet',
  'Building',
  'Guardian',
  'Hero',
  'Huntable',
  'Ship',
]

export const updateMap = new Map([
  ['Damage', 1],
  ['MaximumVelocity', 1],
  ['MaximumRange', 1],
  ['DamageBonus', 1],
  ['Hitpoints', 'hitPoint'],
  ['LOS', 'los'],
])